// Generated by rstantools.  Do not edit by hand.

/*
    igt is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    igt is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with igt.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.32.2
#include <stan/model/model_header.hpp>
namespace model_fit_igt_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 128> locations_array__ =
  {" (found before start of program)",
  " (in 'fit_igt', line 114, column 2 to column 68)",
  " (in 'fit_igt', line 115, column 2 to column 70)",
  " (in 'fit_igt', line 116, column 2 to column 76)",
  " (in 'fit_igt', line 119, column 2 to column 46)",
  " (in 'fit_igt', line 120, column 2 to column 48)",
  " (in 'fit_igt', line 121, column 2 to column 54)",
  " (in 'fit_igt', line 123, column 6 to line 124, column 73)",
  " (in 'fit_igt', line 122, column 37 to line 125, column 3)",
  " (in 'fit_igt', line 122, column 2 to line 125, column 3)",
  " (in 'fit_igt', line 127, column 6 to line 128, column 75)",
  " (in 'fit_igt', line 126, column 38 to line 129, column 3)",
  " (in 'fit_igt', line 126, column 2 to line 129, column 3)",
  " (in 'fit_igt', line 131, column 6 to line 133, column 81)",
  " (in 'fit_igt', line 130, column 41 to line 134, column 3)",
  " (in 'fit_igt', line 130, column 2 to line 134, column 3)",
  " (in 'fit_igt', line 138, column 11 to column 20)",
  " (in 'fit_igt', line 138, column 4 to column 25)",
  " (in 'fit_igt', line 139, column 4 to column 15)",
  " (in 'fit_igt', line 140, column 4 to column 11)",
  " (in 'fit_igt', line 142, column 8 to column 17)",
  " (in 'fit_igt', line 141, column 18 to line 143, column 5)",
  " (in 'fit_igt', line 141, column 4 to line 143, column 5)",
  " (in 'fit_igt', line 147, column 8 to column 73)",
  " (in 'fit_igt', line 149, column 8 to column 49)",
  " (in 'fit_igt', line 151, column 8 to column 71)",
  " (in 'fit_igt', line 153, column 8 to column 74)",
  " (in 'fit_igt', line 145, column 27 to line 154, column 5)",
  " (in 'fit_igt', line 145, column 4 to line 154, column 5)",
  " (in 'fit_igt', line 156, column 4 to column 40)",
  " (in 'fit_igt', line 157, column 4 to column 41)",
  " (in 'fit_igt', line 158, column 4 to column 44)",
  " (in 'fit_igt', line 94, column 2 to column 26)",
  " (in 'fit_igt', line 95, column 2 to column 25)",
  " (in 'fit_igt', line 96, column 2 to column 23)",
  " (in 'fit_igt', line 97, column 2 to column 24)",
  " (in 'fit_igt', line 98, column 2 to column 27)",
  " (in 'fit_igt', line 99, column 2 to column 38)",
  " (in 'fit_igt', line 100, column 2 to column 39)",
  " (in 'fit_igt', line 101, column 2 to column 42)",
  " (in 'fit_igt', line 102, column 27 to column 49)",
  " (in 'fit_igt', line 102, column 2 to column 51)",
  " (in 'fit_igt', line 103, column 28 to column 51)",
  " (in 'fit_igt', line 103, column 2 to column 53)",
  " (in 'fit_igt', line 104, column 31 to column 57)",
  " (in 'fit_igt', line 104, column 2 to column 59)",
  " (in 'fit_igt', line 105, column 27 to column 49)",
  " (in 'fit_igt', line 105, column 2 to column 51)",
  " (in 'fit_igt', line 106, column 28 to column 51)",
  " (in 'fit_igt', line 106, column 2 to column 53)",
  " (in 'fit_igt', line 107, column 31 to column 57)",
  " (in 'fit_igt', line 107, column 2 to column 59)",
  " (in 'fit_igt', line 108, column 11 to column 21)",
  " (in 'fit_igt', line 108, column 2 to column 23)",
  " (in 'fit_igt', line 109, column 12 to column 22)",
  " (in 'fit_igt', line 109, column 2 to column 24)",
  " (in 'fit_igt', line 110, column 14 to column 24)",
  " (in 'fit_igt', line 110, column 2 to column 26)",
  " (in 'fit_igt', line 111, column 2 to column 20)",
  " (in 'fit_igt', line 114, column 44 to column 66)",
  " (in 'fit_igt', line 115, column 45 to column 68)",
  " (in 'fit_igt', line 116, column 48 to column 74)",
  " (in 'fit_igt', line 119, column 22 to column 44)",
  " (in 'fit_igt', line 120, column 23 to column 46)",
  " (in 'fit_igt', line 121, column 26 to column 52)",
  " (in 'fit_igt', line 5, column 4 to column 44)",
  " (in 'fit_igt', line 4, column 49 to line 6, column 1)",
  " (in 'fit_igt', line 10, column 4 to column 26)",
  " (in 'fit_igt', line 14, column 8 to column 48)",
  " (in 'fit_igt', line 13, column 11 to line 15, column 5)",
  " (in 'fit_igt', line 12, column 8 to column 32)",
  " (in 'fit_igt', line 11, column 17 to line 13, column 5)",
  " (in 'fit_igt', line 11, column 4 to line 15, column 5)",
  " (in 'fit_igt', line 9, column 49 to line 16, column 1)",
  " (in 'fit_igt', line 20, column 4 to column 63)",
  " (in 'fit_igt', line 19, column 50 to line 21, column 1)",
  " (in 'fit_igt', line 25, column 11 to column 26)",
  " (in 'fit_igt', line 25, column 4 to column 47)",
  " (in 'fit_igt', line 26, column 4 to column 32)",
  " (in 'fit_igt', line 27, column 4 to column 17)",
  " (in 'fit_igt', line 24, column 59 to line 28, column 1)",
  " (in 'fit_igt', line 32, column 11 to column 26)",
  " (in 'fit_igt', line 32, column 4 to column 38)",
  " (in 'fit_igt', line 33, column 4 to column 56)",
  " (in 'fit_igt', line 34, column 4 to column 17)",
  " (in 'fit_igt', line 31, column 59 to line 35, column 1)",
  " (in 'fit_igt', line 39, column 11 to column 26)",
  " (in 'fit_igt', line 39, column 4 to column 53)",
  " (in 'fit_igt', line 40, column 4 to column 52)",
  " (in 'fit_igt', line 41, column 4 to column 17)",
  " (in 'fit_igt', line 38, column 58 to line 42, column 1)",
  " (in 'fit_igt', line 46, column 4 to column 31)",
  " (in 'fit_igt', line 45, column 40 to line 47, column 1)",
  " (in 'fit_igt', line 51, column 4 to column 32)",
  " (in 'fit_igt', line 50, column 40 to line 52, column 1)",
  " (in 'fit_igt', line 63, column 8 to column 17)",
  " (in 'fit_igt', line 62, column 11 to line 64, column 5)",
  " (in 'fit_igt', line 61, column 8 to column 43)",
  " (in 'fit_igt', line 60, column 24 to line 62, column 5)",
  " (in 'fit_igt', line 60, column 11 to line 64, column 5)",
  " (in 'fit_igt', line 59, column 8 to column 42)",
  " (in 'fit_igt', line 58, column 24 to line 60, column 5)",
  " (in 'fit_igt', line 58, column 11 to line 64, column 5)",
  " (in 'fit_igt', line 57, column 8 to column 42)",
  " (in 'fit_igt', line 56, column 17 to line 58, column 5)",
  " (in 'fit_igt', line 56, column 4 to line 64, column 5)",
  " (in 'fit_igt', line 54, column 54 to line 66, column 1)",
  " (in 'fit_igt', line 77, column 8 to column 17)",
  " (in 'fit_igt', line 76, column 11 to line 78, column 5)",
  " (in 'fit_igt', line 75, column 8 to column 43)",
  " (in 'fit_igt', line 74, column 24 to line 76, column 5)",
  " (in 'fit_igt', line 74, column 11 to line 78, column 5)",
  " (in 'fit_igt', line 73, column 8 to column 44)",
  " (in 'fit_igt', line 72, column 24 to line 74, column 5)",
  " (in 'fit_igt', line 72, column 11 to line 78, column 5)",
  " (in 'fit_igt', line 71, column 8 to column 44)",
  " (in 'fit_igt', line 70, column 17 to line 72, column 5)",
  " (in 'fit_igt', line 70, column 4 to line 78, column 5)",
  " (in 'fit_igt', line 68, column 63 to line 80, column 1)",
  " (in 'fit_igt', line 89, column 8 to column 17)",
  " (in 'fit_igt', line 88, column 11 to line 90, column 5)",
  " (in 'fit_igt', line 87, column 8 to column 39)",
  " (in 'fit_igt', line 86, column 24 to line 88, column 5)",
  " (in 'fit_igt', line 86, column 11 to line 90, column 5)",
  " (in 'fit_igt', line 85, column 8 to column 39)",
  " (in 'fit_igt', line 84, column 17 to line 86, column 5)",
  " (in 'fit_igt', line 84, column 4 to line 90, column 5)",
  " (in 'fit_igt', line 82, column 44 to line 91, column 1)"};
template <typename T0__, typename T1__, typename T2__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_stan_scalar<T1__>,
                              stan::is_stan_scalar<T2__>>* = nullptr>
stan::promote_args_t<T0__, T1__, T2__>
utility_EU(const T0__& win, const T1__& loss, const std::vector<T2__>& par,
           std::ostream* pstream__);
template <typename T0__, typename T1__, typename T2__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_stan_scalar<T1__>,
                              stan::is_stan_scalar<T2__>>* = nullptr>
stan::promote_args_t<T0__, T1__, T2__>
utility_PU(const T0__& win, const T1__& loss, const std::vector<T2__>& par,
           std::ostream* pstream__);
template <typename T0__, typename T1__, typename T2__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_stan_scalar<T1__>,
                              stan::is_stan_scalar<T2__>>* = nullptr>
stan::promote_args_t<T0__, T1__, T2__>
utility_PU2(const T0__& win, const T1__& loss, const std::vector<T2__>& par,
            std::ostream* pstream__);
template <typename T0__, typename T1__, typename T3__,
          stan::require_all_t<stan::is_col_vector<T0__>,
                              stan::is_vt_not_complex<T0__>,
                              stan::is_stan_scalar<T1__>,
                              stan::is_stan_scalar<T3__>>* = nullptr>
Eigen::Matrix<stan::promote_args_t<stan::base_type_t<T0__>, T1__, T3__>,-1,1>
updating_DRL(const T0__& V_arg__, const T1__& u, const int& sel,
             const std::vector<T3__>& par, std::ostream* pstream__);
template <typename T0__, typename T1__, typename T3__,
          stan::require_all_t<stan::is_col_vector<T0__>,
                              stan::is_vt_not_complex<T0__>,
                              stan::is_stan_scalar<T1__>,
                              stan::is_stan_scalar<T3__>>* = nullptr>
Eigen::Matrix<stan::promote_args_t<stan::base_type_t<T0__>, T1__, T3__>,-1,1>
updating_DEL(const T0__& V_arg__, const T1__& u, const int& sel,
             const std::vector<T3__>& par, std::ostream* pstream__);
template <typename T0__, typename T1__, typename T3__,
          stan::require_all_t<stan::is_col_vector<T0__>,
                              stan::is_vt_not_complex<T0__>,
                              stan::is_stan_scalar<T1__>,
                              stan::is_stan_scalar<T3__>>* = nullptr>
Eigen::Matrix<stan::promote_args_t<stan::base_type_t<T0__>, T1__, T3__>,-1,1>
updating_ML(const T0__& V_arg__, const T1__& u, const int& sel,
            const std::vector<T3__>& par, std::ostream* pstream__);
template <typename T1__,
          stan::require_all_t<stan::is_stan_scalar<T1__>>* = nullptr>
stan::promote_args_t<T1__>
temperature_TDC(const int& t, const std::vector<T1__>& par, std::ostream*
                pstream__);
template <typename T1__,
          stan::require_all_t<stan::is_stan_scalar<T1__>>* = nullptr>
stan::promote_args_t<T1__>
temperature_TIC(const int& t, const std::vector<T1__>& par, std::ostream*
                pstream__);
template <typename T0__, typename T1__, typename T2__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_stan_scalar<T1__>,
                              stan::is_stan_scalar<T2__>>* = nullptr>
stan::promote_args_t<T0__, T1__, T2__>
utility(const T0__& win, const T1__& loss, const std::vector<T2__>& par,
        const int& ind, std::ostream* pstream__);
template <typename T0__, typename T1__, typename T3__,
          stan::require_all_t<stan::is_col_vector<T0__>,
                              stan::is_vt_not_complex<T0__>,
                              stan::is_stan_scalar<T1__>,
                              stan::is_stan_scalar<T3__>>* = nullptr>
Eigen::Matrix<stan::promote_args_t<stan::base_type_t<T0__>, T1__, T3__>,-1,1>
updating(const T0__& V_arg__, const T1__& u, const int& sel,
         const std::vector<T3__>& par, const int& ind, std::ostream*
         pstream__);
template <typename T1__,
          stan::require_all_t<stan::is_stan_scalar<T1__>>* = nullptr>
stan::promote_args_t<T1__>
temperature(const int& t, const std::vector<T1__>& par, const int& ind,
            std::ostream* pstream__);
template <typename T0__, typename T1__, typename T2__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_stan_scalar<T1__>,
                              stan::is_stan_scalar<T2__>>*>
stan::promote_args_t<T0__, T1__, T2__>
utility_EU(const T0__& win, const T1__& loss, const std::vector<T2__>& par,
           std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T0__, T1__, T2__>;
  int current_statement__ = 0;
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    current_statement__ = 65;
    return (((1 - stan::model::rvalue(par, "par", stan::model::index_uni(1)))
           * win) -
           (stan::model::rvalue(par, "par", stan::model::index_uni(1)) *
           loss));
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
template <typename T0__, typename T1__, typename T2__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_stan_scalar<T1__>,
                              stan::is_stan_scalar<T2__>>*>
stan::promote_args_t<T0__, T1__, T2__>
utility_PU(const T0__& win, const T1__& loss, const std::vector<T2__>& par,
           std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T0__, T1__, T2__>;
  int current_statement__ = 0;
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    local_scalar_t__ net = DUMMY_VAR__;
    current_statement__ = 67;
    net = (win - loss);
    current_statement__ = 72;
    if (stan::math::logical_gte(net, 0)) {
      current_statement__ = 70;
      return stan::math::pow(net,
               stan::model::rvalue(par, "par", stan::model::index_uni(1)));
    } else {
      current_statement__ = 68;
      return (-stan::model::rvalue(par, "par", stan::model::index_uni(2)) *
             stan::math::pow(stan::math::fabs(net),
               stan::model::rvalue(par, "par", stan::model::index_uni(1))));
    }
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
template <typename T0__, typename T1__, typename T2__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_stan_scalar<T1__>,
                              stan::is_stan_scalar<T2__>>*>
stan::promote_args_t<T0__, T1__, T2__>
utility_PU2(const T0__& win, const T1__& loss, const std::vector<T2__>& par,
            std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T0__, T1__, T2__>;
  int current_statement__ = 0;
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    current_statement__ = 74;
    return (stan::math::pow(win,
              stan::model::rvalue(par, "par", stan::model::index_uni(1)))
           - (stan::model::rvalue(par, "par", stan::model::index_uni(2)) *
           stan::math::pow(stan::math::fabs(loss),
             stan::model::rvalue(par, "par", stan::model::index_uni(1)))));
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
template <typename T0__, typename T1__, typename T3__,
          stan::require_all_t<stan::is_col_vector<T0__>,
                              stan::is_vt_not_complex<T0__>,
                              stan::is_stan_scalar<T1__>,
                              stan::is_stan_scalar<T3__>>*>
Eigen::Matrix<stan::promote_args_t<stan::base_type_t<T0__>, T1__, T3__>,-1,1>
updating_DRL(const T0__& V_arg__, const T1__& u, const int& sel,
             const std::vector<T3__>& par, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<stan::base_type_t<T0__>,
                             T1__, T3__>;
  int current_statement__ = 0;
  const auto& V = stan::math::to_ref(V_arg__);
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    current_statement__ = 76;
    stan::math::validate_non_negative_index("V_new", "num_elements(V)",
      stan::math::num_elements(V));
    Eigen::Matrix<local_scalar_t__,-1,1> V_new =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(stan::math::num_elements(
                                                       V), DUMMY_VAR__);
    current_statement__ = 77;
    stan::model::assign(V_new,
      stan::math::multiply(
        stan::model::rvalue(par, "par", stan::model::index_uni(1)), V),
      "assigning variable V_new");
    current_statement__ = 78;
    stan::model::assign(V_new,
      (stan::model::rvalue(V_new, "V_new", stan::model::index_uni(sel)) + u),
      "assigning variable V_new", stan::model::index_uni(sel));
    current_statement__ = 79;
    return V_new;
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
template <typename T0__, typename T1__, typename T3__,
          stan::require_all_t<stan::is_col_vector<T0__>,
                              stan::is_vt_not_complex<T0__>,
                              stan::is_stan_scalar<T1__>,
                              stan::is_stan_scalar<T3__>>*>
Eigen::Matrix<stan::promote_args_t<stan::base_type_t<T0__>, T1__, T3__>,-1,1>
updating_DEL(const T0__& V_arg__, const T1__& u, const int& sel,
             const std::vector<T3__>& par, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<stan::base_type_t<T0__>,
                             T1__, T3__>;
  int current_statement__ = 0;
  const auto& V = stan::math::to_ref(V_arg__);
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    current_statement__ = 81;
    stan::math::validate_non_negative_index("V_new", "num_elements(V)",
      stan::math::num_elements(V));
    Eigen::Matrix<local_scalar_t__,-1,1> V_new =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(stan::math::num_elements(
                                                       V), DUMMY_VAR__);
    current_statement__ = 82;
    stan::model::assign(V_new, V, "assigning variable V_new");
    current_statement__ = 83;
    stan::model::assign(V_new,
      (stan::model::rvalue(V_new, "V_new", stan::model::index_uni(sel)) +
      (stan::model::rvalue(par, "par", stan::model::index_uni(1)) * (u -
      stan::model::rvalue(V_new, "V_new", stan::model::index_uni(sel))))),
      "assigning variable V_new", stan::model::index_uni(sel));
    current_statement__ = 84;
    return V_new;
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
template <typename T0__, typename T1__, typename T3__,
          stan::require_all_t<stan::is_col_vector<T0__>,
                              stan::is_vt_not_complex<T0__>,
                              stan::is_stan_scalar<T1__>,
                              stan::is_stan_scalar<T3__>>*>
Eigen::Matrix<stan::promote_args_t<stan::base_type_t<T0__>, T1__, T3__>,-1,1>
updating_ML(const T0__& V_arg__, const T1__& u, const int& sel,
            const std::vector<T3__>& par, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<stan::base_type_t<T0__>,
                             T1__, T3__>;
  int current_statement__ = 0;
  const auto& V = stan::math::to_ref(V_arg__);
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    current_statement__ = 86;
    stan::math::validate_non_negative_index("V_new", "num_elements(V)",
      stan::math::num_elements(V));
    Eigen::Matrix<local_scalar_t__,-1,1> V_new =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(stan::math::num_elements(
                                                       V), DUMMY_VAR__);
    current_statement__ = 87;
    stan::model::assign(V_new,
      stan::math::multiply((1 -
        stan::model::rvalue(par, "par", stan::model::index_uni(1))), V),
      "assigning variable V_new");
    current_statement__ = 88;
    stan::model::assign(V_new,
      (stan::model::rvalue(par, "par", stan::model::index_uni(2)) * (u - ((1
      - stan::model::rvalue(par, "par", stan::model::index_uni(1))) *
      stan::model::rvalue(V, "V", stan::model::index_uni(sel))))),
      "assigning variable V_new", stan::model::index_uni(sel));
    current_statement__ = 89;
    return V_new;
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
template <typename T1__, stan::require_all_t<stan::is_stan_scalar<T1__>>*>
stan::promote_args_t<T1__>
temperature_TDC(const int& t, const std::vector<T1__>& par, std::ostream*
                pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T1__>;
  int current_statement__ = 0;
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    current_statement__ = 91;
    return stan::math::pow((t / 10.0),
             stan::model::rvalue(par, "par", stan::model::index_uni(1)));
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
template <typename T1__, stan::require_all_t<stan::is_stan_scalar<T1__>>*>
stan::promote_args_t<T1__>
temperature_TIC(const int& t, const std::vector<T1__>& par, std::ostream*
                pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T1__>;
  int current_statement__ = 0;
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    current_statement__ = 93;
    return (stan::math::pow(3.0,
              stan::model::rvalue(par, "par", stan::model::index_uni(1)))
           - 1);
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
template <typename T0__, typename T1__, typename T2__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_stan_scalar<T1__>,
                              stan::is_stan_scalar<T2__>>*>
stan::promote_args_t<T0__, T1__, T2__>
utility(const T0__& win, const T1__& loss, const std::vector<T2__>& par,
        const int& ind, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T0__, T1__, T2__>;
  int current_statement__ = 0;
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    current_statement__ = 105;
    if (stan::math::logical_eq(ind, 1)) {
      current_statement__ = 103;
      return utility_EU(win, loss, par, pstream__);
    } else {
      current_statement__ = 102;
      if (stan::math::logical_eq(ind, 2)) {
        current_statement__ = 100;
        return utility_PU(win, loss, par, pstream__);
      } else {
        current_statement__ = 99;
        if (stan::math::logical_eq(ind, 3)) {
          current_statement__ = 97;
          return utility_PU2(win, loss, par, pstream__);
        } else {
          current_statement__ = 95;
          return 0;
        }
      }
    }
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
template <typename T0__, typename T1__, typename T3__,
          stan::require_all_t<stan::is_col_vector<T0__>,
                              stan::is_vt_not_complex<T0__>,
                              stan::is_stan_scalar<T1__>,
                              stan::is_stan_scalar<T3__>>*>
Eigen::Matrix<stan::promote_args_t<stan::base_type_t<T0__>, T1__, T3__>,-1,1>
updating(const T0__& V_arg__, const T1__& u, const int& sel,
         const std::vector<T3__>& par, const int& ind, std::ostream*
         pstream__) {
  using local_scalar_t__ = stan::promote_args_t<stan::base_type_t<T0__>,
                             T1__, T3__>;
  int current_statement__ = 0;
  const auto& V = stan::math::to_ref(V_arg__);
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    current_statement__ = 117;
    if (stan::math::logical_eq(ind, 1)) {
      current_statement__ = 115;
      return updating_DRL(V, u, sel, par, pstream__);
    } else {
      current_statement__ = 114;
      if (stan::math::logical_eq(ind, 2)) {
        current_statement__ = 112;
        return updating_DEL(V, u, sel, par, pstream__);
      } else {
        current_statement__ = 111;
        if (stan::math::logical_eq(ind, 3)) {
          current_statement__ = 109;
          return updating_ML(V, u, sel, par, pstream__);
        } else {
          current_statement__ = 107;
          return V;
        }
      }
    }
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
template <typename T1__, stan::require_all_t<stan::is_stan_scalar<T1__>>*>
stan::promote_args_t<T1__>
temperature(const int& t, const std::vector<T1__>& par, const int& ind,
            std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T1__>;
  int current_statement__ = 0;
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    current_statement__ = 126;
    if (stan::math::logical_eq(ind, 1)) {
      current_statement__ = 124;
      return temperature_TDC(t, par, pstream__);
    } else {
      current_statement__ = 123;
      if (stan::math::logical_eq(ind, 2)) {
        current_statement__ = 121;
        return temperature_TIC(t, par, pstream__);
      } else {
        current_statement__ = 119;
        return 1;
      }
    }
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
#include <stan_meta_header.hpp>
class model_fit_igt final : public model_base_crtp<model_fit_igt> {
private:
  int NUM_TRIALS;
  int NUM_DECKS;
  int UTILITY_FUNCTION;
  int UPDATING_FUNCTION;
  int TEMPERATURE_FUNCTION;
  int NUM_UTILITY_PARAMETERS;
  int NUM_UPDATING_PARAMETERS;
  int NUM_TEMPERATURE_PARAMETERS;
  std::vector<double> UTILITY_LOWER_BOUND;
  std::vector<double> UPDATING_LOWER_BOUND;
  std::vector<double> TEMPERATURE_LOWER_BOUND;
  std::vector<double> UTILITY_UPPER_BOUND;
  std::vector<double> UPDATING_UPPER_BOUND;
  std::vector<double> TEMPERATURE_UPPER_BOUND;
  std::vector<double> win;
  std::vector<double> loss;
  std::vector<int> choice;
  double reg;
public:
  ~model_fit_igt() {}
  model_fit_igt(stan::io::var_context& context__, unsigned int
                random_seed__ = 0, std::ostream* pstream__ = nullptr)
      : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "model_fit_igt_namespace::model_fit_igt";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 32;
      context__.validate_dims("data initialization", "NUM_TRIALS", "int",
        std::vector<size_t>{});
      NUM_TRIALS = std::numeric_limits<int>::min();
      current_statement__ = 32;
      NUM_TRIALS = context__.vals_i("NUM_TRIALS")[(1 - 1)];
      current_statement__ = 32;
      stan::math::check_greater_or_equal(function__, "NUM_TRIALS",
        NUM_TRIALS, 0);
      current_statement__ = 33;
      context__.validate_dims("data initialization", "NUM_DECKS", "int",
        std::vector<size_t>{});
      NUM_DECKS = std::numeric_limits<int>::min();
      current_statement__ = 33;
      NUM_DECKS = context__.vals_i("NUM_DECKS")[(1 - 1)];
      current_statement__ = 33;
      stan::math::check_greater_or_equal(function__, "NUM_DECKS", NUM_DECKS,
        0);
      current_statement__ = 34;
      context__.validate_dims("data initialization", "UTILITY_FUNCTION",
        "int", std::vector<size_t>{});
      UTILITY_FUNCTION = std::numeric_limits<int>::min();
      current_statement__ = 34;
      UTILITY_FUNCTION = context__.vals_i("UTILITY_FUNCTION")[(1 - 1)];
      current_statement__ = 35;
      context__.validate_dims("data initialization", "UPDATING_FUNCTION",
        "int", std::vector<size_t>{});
      UPDATING_FUNCTION = std::numeric_limits<int>::min();
      current_statement__ = 35;
      UPDATING_FUNCTION = context__.vals_i("UPDATING_FUNCTION")[(1 - 1)];
      current_statement__ = 36;
      context__.validate_dims("data initialization", "TEMPERATURE_FUNCTION",
        "int", std::vector<size_t>{});
      TEMPERATURE_FUNCTION = std::numeric_limits<int>::min();
      current_statement__ = 36;
      TEMPERATURE_FUNCTION = context__.vals_i("TEMPERATURE_FUNCTION")[(1 -
        1)];
      current_statement__ = 37;
      context__.validate_dims("data initialization",
        "NUM_UTILITY_PARAMETERS", "int", std::vector<size_t>{});
      NUM_UTILITY_PARAMETERS = std::numeric_limits<int>::min();
      current_statement__ = 37;
      NUM_UTILITY_PARAMETERS = context__.vals_i("NUM_UTILITY_PARAMETERS")[(1
        - 1)];
      current_statement__ = 37;
      stan::math::check_greater_or_equal(function__,
        "NUM_UTILITY_PARAMETERS", NUM_UTILITY_PARAMETERS, 0);
      current_statement__ = 38;
      context__.validate_dims("data initialization",
        "NUM_UPDATING_PARAMETERS", "int", std::vector<size_t>{});
      NUM_UPDATING_PARAMETERS = std::numeric_limits<int>::min();
      current_statement__ = 38;
      NUM_UPDATING_PARAMETERS = context__.vals_i("NUM_UPDATING_PARAMETERS")[(1
        - 1)];
      current_statement__ = 38;
      stan::math::check_greater_or_equal(function__,
        "NUM_UPDATING_PARAMETERS", NUM_UPDATING_PARAMETERS, 0);
      current_statement__ = 39;
      context__.validate_dims("data initialization",
        "NUM_TEMPERATURE_PARAMETERS", "int", std::vector<size_t>{});
      NUM_TEMPERATURE_PARAMETERS = std::numeric_limits<int>::min();
      current_statement__ = 39;
      NUM_TEMPERATURE_PARAMETERS = context__.vals_i("NUM_TEMPERATURE_PARAMETERS")[(1
        - 1)];
      current_statement__ = 39;
      stan::math::check_greater_or_equal(function__,
        "NUM_TEMPERATURE_PARAMETERS", NUM_TEMPERATURE_PARAMETERS, 0);
      current_statement__ = 40;
      stan::math::validate_non_negative_index("UTILITY_LOWER_BOUND",
        "NUM_UTILITY_PARAMETERS", NUM_UTILITY_PARAMETERS);
      current_statement__ = 41;
      context__.validate_dims("data initialization", "UTILITY_LOWER_BOUND",
        "double",
        std::vector<size_t>{static_cast<size_t>(NUM_UTILITY_PARAMETERS)});
      UTILITY_LOWER_BOUND = std::vector<double>(NUM_UTILITY_PARAMETERS,
                              std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 41;
      UTILITY_LOWER_BOUND = context__.vals_r("UTILITY_LOWER_BOUND");
      current_statement__ = 42;
      stan::math::validate_non_negative_index("UPDATING_LOWER_BOUND",
        "NUM_UPDATING_PARAMETERS", NUM_UPDATING_PARAMETERS);
      current_statement__ = 43;
      context__.validate_dims("data initialization", "UPDATING_LOWER_BOUND",
        "double",
        std::vector<size_t>{static_cast<size_t>(NUM_UPDATING_PARAMETERS)});
      UPDATING_LOWER_BOUND = std::vector<double>(NUM_UPDATING_PARAMETERS,
                               std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 43;
      UPDATING_LOWER_BOUND = context__.vals_r("UPDATING_LOWER_BOUND");
      current_statement__ = 44;
      stan::math::validate_non_negative_index("TEMPERATURE_LOWER_BOUND",
        "NUM_TEMPERATURE_PARAMETERS", NUM_TEMPERATURE_PARAMETERS);
      current_statement__ = 45;
      context__.validate_dims("data initialization",
        "TEMPERATURE_LOWER_BOUND", "double",
        std::vector<size_t>{static_cast<size_t>(NUM_TEMPERATURE_PARAMETERS)});
      TEMPERATURE_LOWER_BOUND = std::vector<double>(NUM_TEMPERATURE_PARAMETERS,
                                  std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 45;
      TEMPERATURE_LOWER_BOUND = context__.vals_r("TEMPERATURE_LOWER_BOUND");
      current_statement__ = 46;
      stan::math::validate_non_negative_index("UTILITY_UPPER_BOUND",
        "NUM_UTILITY_PARAMETERS", NUM_UTILITY_PARAMETERS);
      current_statement__ = 47;
      context__.validate_dims("data initialization", "UTILITY_UPPER_BOUND",
        "double",
        std::vector<size_t>{static_cast<size_t>(NUM_UTILITY_PARAMETERS)});
      UTILITY_UPPER_BOUND = std::vector<double>(NUM_UTILITY_PARAMETERS,
                              std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 47;
      UTILITY_UPPER_BOUND = context__.vals_r("UTILITY_UPPER_BOUND");
      current_statement__ = 48;
      stan::math::validate_non_negative_index("UPDATING_UPPER_BOUND",
        "NUM_UPDATING_PARAMETERS", NUM_UPDATING_PARAMETERS);
      current_statement__ = 49;
      context__.validate_dims("data initialization", "UPDATING_UPPER_BOUND",
        "double",
        std::vector<size_t>{static_cast<size_t>(NUM_UPDATING_PARAMETERS)});
      UPDATING_UPPER_BOUND = std::vector<double>(NUM_UPDATING_PARAMETERS,
                               std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 49;
      UPDATING_UPPER_BOUND = context__.vals_r("UPDATING_UPPER_BOUND");
      current_statement__ = 50;
      stan::math::validate_non_negative_index("TEMPERATURE_UPPER_BOUND",
        "NUM_TEMPERATURE_PARAMETERS", NUM_TEMPERATURE_PARAMETERS);
      current_statement__ = 51;
      context__.validate_dims("data initialization",
        "TEMPERATURE_UPPER_BOUND", "double",
        std::vector<size_t>{static_cast<size_t>(NUM_TEMPERATURE_PARAMETERS)});
      TEMPERATURE_UPPER_BOUND = std::vector<double>(NUM_TEMPERATURE_PARAMETERS,
                                  std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 51;
      TEMPERATURE_UPPER_BOUND = context__.vals_r("TEMPERATURE_UPPER_BOUND");
      current_statement__ = 52;
      stan::math::validate_non_negative_index("win", "NUM_TRIALS", NUM_TRIALS);
      current_statement__ = 53;
      context__.validate_dims("data initialization", "win", "double",
        std::vector<size_t>{static_cast<size_t>(NUM_TRIALS)});
      win = std::vector<double>(NUM_TRIALS,
              std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 53;
      win = context__.vals_r("win");
      current_statement__ = 54;
      stan::math::validate_non_negative_index("loss", "NUM_TRIALS",
        NUM_TRIALS);
      current_statement__ = 55;
      context__.validate_dims("data initialization", "loss", "double",
        std::vector<size_t>{static_cast<size_t>(NUM_TRIALS)});
      loss = std::vector<double>(NUM_TRIALS,
               std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 55;
      loss = context__.vals_r("loss");
      current_statement__ = 56;
      stan::math::validate_non_negative_index("choice", "NUM_TRIALS",
        NUM_TRIALS);
      current_statement__ = 57;
      context__.validate_dims("data initialization", "choice", "int",
        std::vector<size_t>{static_cast<size_t>(NUM_TRIALS)});
      choice = std::vector<int>(NUM_TRIALS, std::numeric_limits<int>::min());
      current_statement__ = 57;
      choice = context__.vals_i("choice");
      current_statement__ = 58;
      context__.validate_dims("data initialization", "reg", "double",
        std::vector<size_t>{});
      reg = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 58;
      reg = context__.vals_r("reg")[(1 - 1)];
      current_statement__ = 58;
      stan::math::check_greater_or_equal(function__, "reg", reg, 1);
      current_statement__ = 59;
      stan::math::validate_non_negative_index("raw_utility_params",
        "NUM_UTILITY_PARAMETERS", NUM_UTILITY_PARAMETERS);
      current_statement__ = 60;
      stan::math::validate_non_negative_index("raw_updating_params",
        "NUM_UPDATING_PARAMETERS", NUM_UPDATING_PARAMETERS);
      current_statement__ = 61;
      stan::math::validate_non_negative_index("raw_temperature_params",
        "NUM_TEMPERATURE_PARAMETERS", NUM_TEMPERATURE_PARAMETERS);
      current_statement__ = 62;
      stan::math::validate_non_negative_index("utility_params",
        "NUM_UTILITY_PARAMETERS", NUM_UTILITY_PARAMETERS);
      current_statement__ = 63;
      stan::math::validate_non_negative_index("updating_params",
        "NUM_UPDATING_PARAMETERS", NUM_UPDATING_PARAMETERS);
      current_statement__ = 64;
      stan::math::validate_non_negative_index("temperature_params",
        "NUM_TEMPERATURE_PARAMETERS", NUM_TEMPERATURE_PARAMETERS);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = NUM_UTILITY_PARAMETERS + NUM_UPDATING_PARAMETERS +
      NUM_TEMPERATURE_PARAMETERS;
  }
  inline std::string model_name() const final {
    return "model_fit_igt";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.32.2",
             "stancflags = --allow-undefined"};
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "model_fit_igt_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      std::vector<local_scalar_t__> raw_utility_params =
        std::vector<local_scalar_t__>(NUM_UTILITY_PARAMETERS, DUMMY_VAR__);
      current_statement__ = 1;
      raw_utility_params = in__.template read_constrain_lub<
                             std::vector<local_scalar_t__>, jacobian__>(0, 1,
                             lp__, NUM_UTILITY_PARAMETERS);
      std::vector<local_scalar_t__> raw_updating_params =
        std::vector<local_scalar_t__>(NUM_UPDATING_PARAMETERS, DUMMY_VAR__);
      current_statement__ = 2;
      raw_updating_params = in__.template read_constrain_lub<
                              std::vector<local_scalar_t__>, jacobian__>(0,
                              1, lp__, NUM_UPDATING_PARAMETERS);
      std::vector<local_scalar_t__> raw_temperature_params =
        std::vector<local_scalar_t__>(NUM_TEMPERATURE_PARAMETERS,
          DUMMY_VAR__);
      current_statement__ = 3;
      raw_temperature_params = in__.template read_constrain_lub<
                                 std::vector<local_scalar_t__>,
                                 jacobian__>(0, 1, lp__,
                                 NUM_TEMPERATURE_PARAMETERS);
      std::vector<local_scalar_t__> utility_params =
        std::vector<local_scalar_t__>(NUM_UTILITY_PARAMETERS, DUMMY_VAR__);
      std::vector<local_scalar_t__> updating_params =
        std::vector<local_scalar_t__>(NUM_UPDATING_PARAMETERS, DUMMY_VAR__);
      std::vector<local_scalar_t__> temperature_params =
        std::vector<local_scalar_t__>(NUM_TEMPERATURE_PARAMETERS,
          DUMMY_VAR__);
      current_statement__ = 9;
      for (int i = 1; i <= NUM_UTILITY_PARAMETERS; ++i) {
        current_statement__ = 7;
        stan::model::assign(utility_params,
          (((stan::model::rvalue(UTILITY_UPPER_BOUND, "UTILITY_UPPER_BOUND",
               stan::model::index_uni(i)) -
          stan::model::rvalue(UTILITY_LOWER_BOUND, "UTILITY_LOWER_BOUND",
            stan::model::index_uni(i))) *
          stan::model::rvalue(raw_utility_params, "raw_utility_params",
            stan::model::index_uni(i))) +
          stan::model::rvalue(UTILITY_LOWER_BOUND, "UTILITY_LOWER_BOUND",
            stan::model::index_uni(i))), "assigning variable utility_params",
          stan::model::index_uni(i));
      }
      current_statement__ = 12;
      for (int i = 1; i <= NUM_UPDATING_PARAMETERS; ++i) {
        current_statement__ = 10;
        stan::model::assign(updating_params,
          (((stan::model::rvalue(UPDATING_UPPER_BOUND,
               "UPDATING_UPPER_BOUND", stan::model::index_uni(i)) -
          stan::model::rvalue(UPDATING_LOWER_BOUND, "UPDATING_LOWER_BOUND",
            stan::model::index_uni(i))) *
          stan::model::rvalue(raw_updating_params, "raw_updating_params",
            stan::model::index_uni(i))) +
          stan::model::rvalue(UPDATING_LOWER_BOUND, "UPDATING_LOWER_BOUND",
            stan::model::index_uni(i))),
          "assigning variable updating_params", stan::model::index_uni(i));
      }
      current_statement__ = 15;
      for (int i = 1; i <= NUM_TEMPERATURE_PARAMETERS; ++i) {
        current_statement__ = 13;
        stan::model::assign(temperature_params,
          (((stan::model::rvalue(TEMPERATURE_UPPER_BOUND,
               "TEMPERATURE_UPPER_BOUND", stan::model::index_uni(i)) -
          stan::model::rvalue(TEMPERATURE_LOWER_BOUND,
            "TEMPERATURE_LOWER_BOUND", stan::model::index_uni(i))) *
          stan::model::rvalue(raw_temperature_params,
            "raw_temperature_params", stan::model::index_uni(i))) +
          stan::model::rvalue(TEMPERATURE_LOWER_BOUND,
            "TEMPERATURE_LOWER_BOUND", stan::model::index_uni(i))),
          "assigning variable temperature_params", stan::model::index_uni(i));
      }
      {
        current_statement__ = 16;
        stan::math::validate_non_negative_index("V", "NUM_DECKS", NUM_DECKS);
        Eigen::Matrix<local_scalar_t__,-1,1> V =
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(NUM_DECKS,
            DUMMY_VAR__);
        local_scalar_t__ theta = DUMMY_VAR__;
        local_scalar_t__ U = DUMMY_VAR__;
        current_statement__ = 22;
        for (int d = 1; d <= 4; ++d) {
          current_statement__ = 20;
          stan::model::assign(V, 0, "assigning variable V",
            stan::model::index_uni(d));
        }
        current_statement__ = 28;
        for (int t = 1; t <= NUM_TRIALS; ++t) {
          current_statement__ = 23;
          theta = temperature(t, temperature_params, TEMPERATURE_FUNCTION,
                    pstream__);
          current_statement__ = 24;
          lp_accum__.add(stan::math::categorical_logit_lpmf<propto__>(
                           stan::model::rvalue(choice, "choice",
                             stan::model::index_uni(t)),
                           stan::math::multiply(theta, V)));
          current_statement__ = 25;
          U = utility(
                stan::model::rvalue(win, "win", stan::model::index_uni(t)),
                stan::model::rvalue(loss, "loss", stan::model::index_uni(t)),
                utility_params, UTILITY_FUNCTION, pstream__);
          current_statement__ = 26;
          stan::model::assign(V,
            updating(stan::model::deep_copy(V), U,
              stan::model::rvalue(choice, "choice", stan::model::index_uni(t)),
              updating_params, UPDATING_FUNCTION, pstream__),
            "assigning variable V");
        }
        current_statement__ = 29;
        lp_accum__.add(stan::math::beta_lpdf<propto__>(raw_utility_params,
                         reg, reg));
        current_statement__ = 30;
        lp_accum__.add(stan::math::beta_lpdf<propto__>(raw_updating_params,
                         reg, reg));
        current_statement__ = 31;
        lp_accum__.add(stan::math::beta_lpdf<propto__>(
                         raw_temperature_params, reg, reg));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    static constexpr const char* function__ =
      "model_fit_igt_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      std::vector<double> raw_utility_params =
        std::vector<double>(NUM_UTILITY_PARAMETERS,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 1;
      raw_utility_params = in__.template read_constrain_lub<
                             std::vector<local_scalar_t__>, jacobian__>(0, 1,
                             lp__, NUM_UTILITY_PARAMETERS);
      std::vector<double> raw_updating_params =
        std::vector<double>(NUM_UPDATING_PARAMETERS,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 2;
      raw_updating_params = in__.template read_constrain_lub<
                              std::vector<local_scalar_t__>, jacobian__>(0,
                              1, lp__, NUM_UPDATING_PARAMETERS);
      std::vector<double> raw_temperature_params =
        std::vector<double>(NUM_TEMPERATURE_PARAMETERS,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 3;
      raw_temperature_params = in__.template read_constrain_lub<
                                 std::vector<local_scalar_t__>,
                                 jacobian__>(0, 1, lp__,
                                 NUM_TEMPERATURE_PARAMETERS);
      std::vector<double> utility_params =
        std::vector<double>(NUM_UTILITY_PARAMETERS,
          std::numeric_limits<double>::quiet_NaN());
      std::vector<double> updating_params =
        std::vector<double>(NUM_UPDATING_PARAMETERS,
          std::numeric_limits<double>::quiet_NaN());
      std::vector<double> temperature_params =
        std::vector<double>(NUM_TEMPERATURE_PARAMETERS,
          std::numeric_limits<double>::quiet_NaN());
      out__.write(raw_utility_params);
      out__.write(raw_updating_params);
      out__.write(raw_temperature_params);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      current_statement__ = 9;
      for (int i = 1; i <= NUM_UTILITY_PARAMETERS; ++i) {
        current_statement__ = 7;
        stan::model::assign(utility_params,
          (((stan::model::rvalue(UTILITY_UPPER_BOUND, "UTILITY_UPPER_BOUND",
               stan::model::index_uni(i)) -
          stan::model::rvalue(UTILITY_LOWER_BOUND, "UTILITY_LOWER_BOUND",
            stan::model::index_uni(i))) *
          stan::model::rvalue(raw_utility_params, "raw_utility_params",
            stan::model::index_uni(i))) +
          stan::model::rvalue(UTILITY_LOWER_BOUND, "UTILITY_LOWER_BOUND",
            stan::model::index_uni(i))), "assigning variable utility_params",
          stan::model::index_uni(i));
      }
      current_statement__ = 12;
      for (int i = 1; i <= NUM_UPDATING_PARAMETERS; ++i) {
        current_statement__ = 10;
        stan::model::assign(updating_params,
          (((stan::model::rvalue(UPDATING_UPPER_BOUND,
               "UPDATING_UPPER_BOUND", stan::model::index_uni(i)) -
          stan::model::rvalue(UPDATING_LOWER_BOUND, "UPDATING_LOWER_BOUND",
            stan::model::index_uni(i))) *
          stan::model::rvalue(raw_updating_params, "raw_updating_params",
            stan::model::index_uni(i))) +
          stan::model::rvalue(UPDATING_LOWER_BOUND, "UPDATING_LOWER_BOUND",
            stan::model::index_uni(i))),
          "assigning variable updating_params", stan::model::index_uni(i));
      }
      current_statement__ = 15;
      for (int i = 1; i <= NUM_TEMPERATURE_PARAMETERS; ++i) {
        current_statement__ = 13;
        stan::model::assign(temperature_params,
          (((stan::model::rvalue(TEMPERATURE_UPPER_BOUND,
               "TEMPERATURE_UPPER_BOUND", stan::model::index_uni(i)) -
          stan::model::rvalue(TEMPERATURE_LOWER_BOUND,
            "TEMPERATURE_LOWER_BOUND", stan::model::index_uni(i))) *
          stan::model::rvalue(raw_temperature_params,
            "raw_temperature_params", stan::model::index_uni(i))) +
          stan::model::rvalue(TEMPERATURE_LOWER_BOUND,
            "TEMPERATURE_LOWER_BOUND", stan::model::index_uni(i))),
          "assigning variable temperature_params", stan::model::index_uni(i));
      }
      if (emit_transformed_parameters__) {
        out__.write(utility_params);
        out__.write(updating_params);
        out__.write(temperature_params);
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      std::vector<local_scalar_t__> raw_utility_params =
        std::vector<local_scalar_t__>(NUM_UTILITY_PARAMETERS, DUMMY_VAR__);
      current_statement__ = 1;
      stan::model::assign(raw_utility_params,
        in__.read<std::vector<local_scalar_t__>>(NUM_UTILITY_PARAMETERS),
        "assigning variable raw_utility_params");
      out__.write_free_lub(0, 1, raw_utility_params);
      std::vector<local_scalar_t__> raw_updating_params =
        std::vector<local_scalar_t__>(NUM_UPDATING_PARAMETERS, DUMMY_VAR__);
      current_statement__ = 2;
      stan::model::assign(raw_updating_params,
        in__.read<std::vector<local_scalar_t__>>(NUM_UPDATING_PARAMETERS),
        "assigning variable raw_updating_params");
      out__.write_free_lub(0, 1, raw_updating_params);
      std::vector<local_scalar_t__> raw_temperature_params =
        std::vector<local_scalar_t__>(NUM_TEMPERATURE_PARAMETERS,
          DUMMY_VAR__);
      current_statement__ = 3;
      stan::model::assign(raw_temperature_params,
        in__.read<std::vector<local_scalar_t__>>(NUM_TEMPERATURE_PARAMETERS),
        "assigning variable raw_temperature_params");
      out__.write_free_lub(0, 1, raw_temperature_params);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization",
        "raw_utility_params", "double",
        std::vector<size_t>{static_cast<size_t>(NUM_UTILITY_PARAMETERS)});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization",
        "raw_updating_params", "double",
        std::vector<size_t>{static_cast<size_t>(NUM_UPDATING_PARAMETERS)});
      current_statement__ = 3;
      context__.validate_dims("parameter initialization",
        "raw_temperature_params", "double",
        std::vector<size_t>{static_cast<size_t>(NUM_TEMPERATURE_PARAMETERS)});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      std::vector<local_scalar_t__> raw_utility_params =
        std::vector<local_scalar_t__>(NUM_UTILITY_PARAMETERS, DUMMY_VAR__);
      current_statement__ = 1;
      raw_utility_params = context__.vals_r("raw_utility_params");
      out__.write_free_lub(0, 1, raw_utility_params);
      std::vector<local_scalar_t__> raw_updating_params =
        std::vector<local_scalar_t__>(NUM_UPDATING_PARAMETERS, DUMMY_VAR__);
      current_statement__ = 2;
      raw_updating_params = context__.vals_r("raw_updating_params");
      out__.write_free_lub(0, 1, raw_updating_params);
      std::vector<local_scalar_t__> raw_temperature_params =
        std::vector<local_scalar_t__>(NUM_TEMPERATURE_PARAMETERS,
          DUMMY_VAR__);
      current_statement__ = 3;
      raw_temperature_params = context__.vals_r("raw_temperature_params");
      out__.write_free_lub(0, 1, raw_temperature_params);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"raw_utility_params",
                "raw_updating_params", "raw_temperature_params"};
    if (emit_transformed_parameters__) {
      std::vector<std::string>
        temp{"utility_params", "updating_params", "temperature_params"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{static_cast<
                                                                    size_t>(
                                                                    NUM_UTILITY_PARAMETERS)},
                std::vector<size_t>{static_cast<size_t>(
                                      NUM_UPDATING_PARAMETERS)},
                std::vector<size_t>{static_cast<size_t>(
                                      NUM_TEMPERATURE_PARAMETERS)}};
    if (emit_transformed_parameters__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(NUM_UTILITY_PARAMETERS)},
             std::vector<size_t>{static_cast<size_t>(NUM_UPDATING_PARAMETERS)},
             std::vector<size_t>{static_cast<size_t>(
                                   NUM_TEMPERATURE_PARAMETERS)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= NUM_UTILITY_PARAMETERS; ++sym1__) {
      param_names__.emplace_back(std::string() + "raw_utility_params" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= NUM_UPDATING_PARAMETERS; ++sym1__) {
      param_names__.emplace_back(std::string() + "raw_updating_params" + '.'
        + std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= NUM_TEMPERATURE_PARAMETERS; ++sym1__) {
      param_names__.emplace_back(std::string() + "raw_temperature_params" +
        '.' + std::to_string(sym1__));
    }
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= NUM_UTILITY_PARAMETERS; ++sym1__) {
        param_names__.emplace_back(std::string() + "utility_params" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= NUM_UPDATING_PARAMETERS; ++sym1__) {
        param_names__.emplace_back(std::string() + "updating_params" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= NUM_TEMPERATURE_PARAMETERS; ++sym1__) {
        param_names__.emplace_back(std::string() + "temperature_params" + '.'
          + std::to_string(sym1__));
      }
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= NUM_UTILITY_PARAMETERS; ++sym1__) {
      param_names__.emplace_back(std::string() + "raw_utility_params" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= NUM_UPDATING_PARAMETERS; ++sym1__) {
      param_names__.emplace_back(std::string() + "raw_updating_params" + '.'
        + std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= NUM_TEMPERATURE_PARAMETERS; ++sym1__) {
      param_names__.emplace_back(std::string() + "raw_temperature_params" +
        '.' + std::to_string(sym1__));
    }
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= NUM_UTILITY_PARAMETERS; ++sym1__) {
        param_names__.emplace_back(std::string() + "utility_params" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= NUM_UPDATING_PARAMETERS; ++sym1__) {
        param_names__.emplace_back(std::string() + "updating_params" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= NUM_TEMPERATURE_PARAMETERS; ++sym1__) {
        param_names__.emplace_back(std::string() + "temperature_params" + '.'
          + std::to_string(sym1__));
      }
    }
    if (emit_generated_quantities__) {}
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"raw_utility_params\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(NUM_UTILITY_PARAMETERS) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"parameters\"},{\"name\":\"raw_updating_params\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(NUM_UPDATING_PARAMETERS) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"parameters\"},{\"name\":\"raw_temperature_params\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(NUM_TEMPERATURE_PARAMETERS) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"parameters\"},{\"name\":\"utility_params\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(NUM_UTILITY_PARAMETERS) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"transformed_parameters\"},{\"name\":\"updating_params\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(NUM_UPDATING_PARAMETERS) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"transformed_parameters\"},{\"name\":\"temperature_params\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(NUM_TEMPERATURE_PARAMETERS) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"transformed_parameters\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"raw_utility_params\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(NUM_UTILITY_PARAMETERS) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"parameters\"},{\"name\":\"raw_updating_params\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(NUM_UPDATING_PARAMETERS) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"parameters\"},{\"name\":\"raw_temperature_params\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(NUM_TEMPERATURE_PARAMETERS) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"parameters\"},{\"name\":\"utility_params\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(NUM_UTILITY_PARAMETERS) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"transformed_parameters\"},{\"name\":\"updating_params\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(NUM_UPDATING_PARAMETERS) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"transformed_parameters\"},{\"name\":\"temperature_params\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(NUM_TEMPERATURE_PARAMETERS) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"transformed_parameters\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = ((NUM_UTILITY_PARAMETERS +
      NUM_UPDATING_PARAMETERS) + NUM_TEMPERATURE_PARAMETERS);
    const size_t num_transformed = emit_transformed_parameters *
      (((NUM_UTILITY_PARAMETERS + NUM_UPDATING_PARAMETERS) +
      NUM_TEMPERATURE_PARAMETERS));
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = ((NUM_UTILITY_PARAMETERS +
      NUM_UPDATING_PARAMETERS) + NUM_TEMPERATURE_PARAMETERS);
    const size_t num_transformed = emit_transformed_parameters *
      (((NUM_UTILITY_PARAMETERS + NUM_UPDATING_PARAMETERS) +
      NUM_TEMPERATURE_PARAMETERS));
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = model_fit_igt_namespace::model_fit_igt;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_fit_igt_namespace::profiles__;
}
#endif
#endif
